Repository FACG4/Care-And-Share-App, pull requests merged in 2018-08, with the labels that each got.

#27 fix: header front-end refactor code
  frontend/src/components/Header/HeaderTitle/HeaderTitle.js
  frontend/src/components/Header/Notifications/Notification/Notification.js
  frontend/src/components/Header/Notifications/index.js
  frontend/src/components/Header/Notifications/style.css
  frontend/src/components/Header/index.js
Labels: approved, urgent

#22 Connection
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/AppRoutes.js
  frontend/src/components/Connections/Connection/Connection.js
  frontend/src/components/Connections/Connection/image.js
  frontend/src/components/Connections/Connection/imageModal.js
  frontend/src/components/Connections/Connections.js
  frontend/src/components/Connections/style.css
  frontend/src/components/singup/singup.js
  frontend/src/components/singup/singupInput.js
  frontend/src/components/singup/style.css
Labels: approved

#29 making chat component and fix style issues relate to issue #7
  frontend/src/components/Chats/Chats.js
  frontend/src/components/Chats/styles.css
Labels: approved, exist-conflicts, request-changes

#26 public profile front-end
  frontend/src/components/Profile/Profile.js
  frontend/src/components/Profile/ProfileForm/ProfileForm.js
  frontend/src/components/Profile/index.js
  frontend/src/components/Profile/style.css
Labels: approved

#31 connection backend
  backend/controllers/index.js
  backend/controllers/mYFriends.js
  backend/database/build.sql
  backend/database/queries/friend.js
  frontend/package-lock.json
  frontend/src/AppRoutes.js
  frontend/src/components/Connections/Connection/image.js
  frontend/src/components/Connections/Connection/imageModal.js
  frontend/src/components/Connections/Connections.js
Labels: exist-conflicts, request-changes, under-revision

#33 Public profile backend
  backend/controllers/index.js
  backend/controllers/profile.js
  backend/database/queries/profile.js
Labels: exist-conflicts, request-changes, under-revision
